create table if not exists users(
    id bigint generated by default as identity not null,
    name varchar(250) not null,
    email varchar(254) unique not null,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

create table if not exists categories(
    id bigint generated by default as identity not null,
    name varchar unique not null,
    CONSTRAINT categories_users PRIMARY KEY (id)
);

create table if not exists events(
    id bigint generated by default as identity not null,
    annotation varchar,
    categories_id bigint REFERENCES categories (id),
    confirmed_requests bigint,
    created_on timestamp(0),
    description varchar,
    event_date timestamp(0),
    initiator_id bigint REFERENCES users (id) on delete cascade,
    lat decimal,
    lon decimal,
    paid boolean,
    participant_limit bigint,
    published_on timestamp(0),
    request_moderation boolean,
    state varchar,
    title varchar,
    views bigint,
    CONSTRAINT events_users PRIMARY KEY (id)
);

create table if not exists requests(
    id bigint generated by default as identity not null,
    created timestamp(0),
    event bigint references events (id) on delete cascade,
    requester bigint references users (id) on delete cascade,
    status varchar(30),
    CONSTRAINT requests_users PRIMARY KEY (id)
);

create table if not exists compilations(
    id bigint generated by default as identity not null,
    pinned boolean,
    title varchar,
    CONSTRAINT compilations_id PRIMARY KEY (id)
);

create table if not exists compilations_events(
    compilations_id bigint references compilations (id) on delete cascade,
    events_id bigint references events (id) on delete cascade

);


